// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhfpcuefguddxtagnzoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoZnBjdWVmZ3VkZHh0YWduem9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTAzODgsImV4cCI6MjA1OTU4NjM4OH0.ZTp94JLNS5oYIRBr6TGrnVYJDnWd8LMc8FaxfBjqkec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);